name: cs-test

initial_conditions: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
optimizer_budget: 7000
n_steps: 20

equation: 
  CellSignal: {}
ansatz:
  ULA:
    n_qubits: 3
    depth: 3

cost:
  EulerCost:
    tau: 0.01
    backend_type: exact

