name: chemo-final

initial_conditions: [1.0, 0.0, 0.2, 0.0]
optimizer_budget: 4000
n_steps: 500

equation: 
  Chemotherapy: {}
ansatz:
  ULA:
    n_qubits: 2
    depth: 2

cost:
  EulerCost:
    tau: 0.1
    backend_type: exact

